---
deployment:
  tasks:
    - export DEPLOYPATH=/home/qcczxjxq/public_html/staging.qcczxjxqycuvbszf.myecosite.com/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH